get http://localhost:3000/api/v1/attendees HTTP/1.1
###
post http://localhost:3000/api/v1/attendee HTTP/1.1
content-type: application/json

{
    "name": "Petar",
    "email": "marko.manojlovic@quantox.com",
    "age": 29
}